# Use postgres/example user/password credentials
version: '3.9'

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  dns:
    image: jpillora/dnsmasq
    container_name: mockdns
    restart: always
    ports:
      - "53:53/udp" # DNS сервер
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf

  adminer:
    image: adminer
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"